version: '3.7'

services:
  lighthouse:
    image: ${DOCKER_REGISTRY-}lighthouse
    build:
      context: hosts
      dockerfile: lighthouse/Dockerfile
    environment:
      - CLUSTER_SEEDS="akka.tcp://paassystem@lighthouse:5053"
      - CLUSTER_IP="lighthouse"
      - CLUSTER_PORT=5053

  btm.paas:
    image: ${DOCKER_REGISTRY-}btmpaas
    build:
      context: hosts
      dockerfile: paas/Dockerfile
    environment:
      - CLUSTER_SEEDS="akka.tcp://paassystem@lighthouse:5053"
      - CLUSTER_PORT=5066
    depends_on:
      - lighthouse

  btm.web.app:
    image: ${DOCKER_REGISTRY-}btmwebapp
    build:
      context: hosts
      dockerfile: web/btm.web.app/Dockerfile
    environment:
      - CLUSTER_SEEDS="akka.tcp://paassystem@lighthouse:5053"
      - CLUSTER_PORT=5077
    depends_on:
      - lighthouse