akka {
    actor {
        provider = cluster

        deployment {
            /bridge/paas {
                router = round-robin-group
                routees.paths = ["/user/paas"]
                nr-of-instances = 100
                cluster {
                    enabled = on
                    max-nr-of-instances-per-node = 1
                    use-role = paas-instance
                }
            }
        }
    }

    remote {
        dot-netty.tcp {
            hostname = "127.0.0.1"
            port = 45077
        }
    }

    cluster {
        seed-nodes = ["akka.tcp://paassystem@127.0.0.1:45053"]
        roles = [web]
    }
}