akka {
    actor {
        provider = cluster
    }

    remote {
        dot-netty.tcp {
            hostname = "127.0.0.1"
            port = 45053
        }
    }

    cluster {
        seed-nodes = ["akka.tcp://paassystem@127.0.0.1:45053"]
        roles = [lighthouse]
    }
}